# Generated by Django 2.1.1 on 2018-10-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0015_auto_20181029_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.ManyToManyField(to='zappyapp.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
