# Generated by Django 2.1.1 on 2018-10-31 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zappyapp', '0018_auto_20181030_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.ManyToManyField(blank=True, to='zappyapp.Product'),
        ),
    ]
