# Generated by Django 2.1.1 on 2018-10-31 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0019_auto_20181031_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zappyapp.Product'),
        ),
    ]
