# Generated by Django 2.1.1 on 2018-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0021_auto_20181031_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.AddField(
            model_name='order',
            name='pids',
            field=models.TextField(null=True),
        ),
    ]
