# Generated by Django 2.1.1 on 2018-11-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0024_auto_20181102_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_address',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
